"""add users table

Revision ID: 08c8618d6a0a
Revises: 9c0083885caf
Create Date: 2025-10-16 16:49:58.649483

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08c8618d6a0a"
down_revision: str | Sequence[str] | None = "9c0083885caf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        "idx_users_created",
        "users",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_users_username",
        "users",
        ["username"],
        unique=False,
        postgresql_where=sa.text("username IS NOT NULL"),
    )
    op.drop_index(op.f("idx_messages_created"), table_name="messages")
    op.create_index(
        "idx_messages_created",
        "messages",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index(op.f("idx_messages_lookup"), table_name="messages")
    op.create_index(
        "idx_messages_lookup",
        "messages",
        ["chat_id", "user_id", "deleted_at", "created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_messages_lookup", table_name="messages", postgresql_ops={"created_at": "DESC"}
    )
    op.create_index(
        op.f("idx_messages_lookup"),
        "messages",
        ["chat_id", "user_id", "deleted_at", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_messages_created", table_name="messages", postgresql_ops={"created_at": "DESC"}
    )
    op.create_index(
        op.f("idx_messages_created"),
        "messages",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index(
        "idx_users_username", table_name="users", postgresql_where=sa.text("username IS NOT NULL")
    )
    op.drop_index("idx_users_created", table_name="users", postgresql_ops={"created_at": "DESC"})
    op.drop_table("users")
    # ### end Alembic commands ###
